### ISSUE TITLE
delete blog?

### ISSUE THREAD

**Issue by kamontat** [Database-Systems-For-SKE/Frontend#1]
ลบ blog ดีไหมอะ?

**Comment by maymaays** [comment]
blog ตรงไหน 
<img width="1059" alt="screen shot 2560-04-07 at 11 19 40 am" src="https://cloud.githubusercontent.com/assets/17776844/24785453/1ff9906e-1b84-11e7-9ad0-387499fe942c.png">
อันนี้ป่ะะ ?
ถ้าใช่ เค้ายังแก้ไม่เสร็จ กะจะใส่เป็น team manager

**Comment by kamontat** [comment]
I think you already deleted.
