### ISSUE TITLE
Why have node_module ?

### ISSUE THREAD

**Issue by kamontat** [Database-Systems-For-SKE/Frontend#6]
ทำไมถึงมี [node folder](https://github.com/Database-Systems-For-SKE/Frontend/tree/master/node_modules/jquery) มาด้วยอะ?

**Comment by kamontat** [comment]
@Database-Systems-For-SKE/frontend

**Comment by maymaays** [comment]
ลบแล้วว ตอนแรกกะจะลองใช้ดู
